from subprocess import *
import time
Popen('python ./HistoryPrice_11.py')
time.sleep(1)
Popen('python ./HistoryPrice_12.py')
# time.sleep(1)
# Popen('python ./HistoryPrice_14.py')
# time.sleep(1)
# Popen('python ./HistoryPrice_15.py')
# time.sleep(1)
# Popen('python ./HistoryPrice_16.py')
# time.sleep(1)
# Popen('python ./HistoryPrice_17.py')
# time.sleep(5)
# Popen('python ./HistoryPrice_18.py')
# time.sleep(5)
# Popen('python ./HistoryPrice_19.py')
# time.sleep(5)
# Popen('python ./HistoryPrice_20.py')
# time.sleep(5)
